name: Build and test
on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions: write-all

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yml

#  test:
#    needs: build
#    uses: ./.github/workflows/test.yml
#    secrets: inherit

  release:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      docker_version: ${{ steps.semantic_release.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Create release
        run: npm run release || { echo "No release created. Exiting."; exit 0; }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get release version
        id: version
        run: |
          version=$(npm pkg get version | tr -d '"')
          echo "Found version: ${version}" 
          echo "version=${version}" >> $GITHUB_OUTPUT
      - name: Debug version
        run: echo "Version is ${{ steps.version.outputs.version}}"
  deploy:
    needs: release
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: earthcode-openeo-publisher
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - name: Create .env file
        run: | 
          echo "AUTH_SECRET=${{ secrets.AUTH_SECRET }}" >> .env
          echo "AUTH_GITHUB_ID=${{ secrets.AUTH_GITHUB_ID }}" >> .env
          echo "AUTH_GITHUB_SECRET=${{ secrets.AUTH_GITHUB_SECRET }}" >> .env
          echo "AUTH_TRUST_HOST=true" >> .env
          echo "NEXT_PUBLIC_GITHUB_OWNER=ESA-EarthCODE" >> .env
          echo "NEXT_PUBLIC_GITHUB_REPO=open-science-catalog-metadata-testing" >> .env
          echo "NEXT_PUBLIC_GITHUB_REF_BRANCH=workflows-experiments-2" >> .env
          echo "NEXT_PUBLIC_OPENEO_BACKENDS=https://openeofed.dataspace.copernicus.eu/openeo" >> .env
      - run: npm install
      - name: Login to Docker repository
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_ARTIFACTORY }}
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}
      - name: Build image
        run: |
          docker build \
           --build-arg NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} \
           -t $DOCKER_IMAGE_NAME .
      - name: Tag image
        run: |
          docker tag $DOCKER_IMAGE_NAME ${{ secrets.DOCKER_ARTIFACTORY }}/$DOCKER_IMAGE_NAME:${{ needs.release.outputs.docker_version }} 
          docker tag $DOCKER_IMAGE_NAME  ${{ secrets.DOCKER_ARTIFACTORY }}/$DOCKER_IMAGE_NAME:latest
      - name: Push image
        run: |
          docker push ${{ secrets.DOCKER_ARTIFACTORY }}/$DOCKER_IMAGE_NAME:${{needs.release.outputs.docker_version}} 
          docker push ${{ secrets.DOCKER_ARTIFACTORY }}/$DOCKER_IMAGE_NAME:latest
