name: Review PR
on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize ]
  workflow_dispatch:

jobs:
  build-pr:
    uses: ./.github/workflows/build.yml

  test-pr:
    needs: build-pr
    uses: ./.github/workflows/test.yml
